Update GitHubSCMSource.java
jenkinsci/github-branch-source-plugin pull request #421
Opened 2021-04-30 17:16 UTC by JaredEgolf

GitHub is in specific limited cases producing a single underscore in an account name.

# Description

A brief summary describing the changes in this pull request. See 
[JENKINS-XXXXX](https://issues.jenkins-ci.org/browse/JENKINS-XXXXX) for further information. 

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [ ] Automated tests have been added to exercise the changes
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verify that the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

# Documentation changes
- [ ] Link to jenkins.io PR, or an explanation for why no doc changes are needed
_This is to support existing Jenkins and GitHub users who brought this blocker to our attention and will require this modification._

# Users/aliases to notify

2021-04-30 17:41 UTC, bitwiseman requested changes
There needs to be regression tests for this. 
Also, could you point to a real-world example?  Just for completeness.

2021-05-01 03:39 UTC, bikwan commented
https://github.com/pj_nitin is a valid user name.

2021-05-01 03:39 UTC, bikwan commented
as @bitwiseman mentioned, please add a test to ensure that underscores are properly tested.

2021-05-06 20:51 UTC, JaredEgolf commented
> There needs to be regression tests for this.
I could use some help with this.

2021-06-04 21:31 UTC, bitwiseman approved these changes

2021-06-04 21:36 UTC, bitwiseman requested changes
@JaredEgolf 
Add some tests that run that regular expression with various inputs and assert that they match.   
You can ignore most of the complex stuff and use a simple JUnit test method.

2022-03-21 20:31 UTC, spstarr commented
Please merge this change, it breaks Github EMU users which *must* have an underscore _ in their username. This is an absolute requirement.

2022-03-21 20:38 UTC, vikramarsid commented
@bitwiseman Any update on this PR?

2022-03-21 20:43 UTC, vikramarsid commented
I don't think regex in the PR doesn't work in all cases. Needs `^[A-Za-z0-9](?:[A-Za-z0-9_]|-(?=[A-Za-z0-9])){0,38}$`

2022-03-21 20:43 UTC, spstarr commented
```
diff --git a/src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java b/src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java
index 90447de..560a7e2 100644
--- a/src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java
+++ b/src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java
@@ -151,7 +151,7 @@ public class GitHubSCMSource extends AbstractGitSCMSource {
 
   public static final String VALID_GITHUB_REPO_NAME = "^[0-9A-Za-z._-]+$";
   public static final String VALID_GITHUB_USER_NAME =
-      "^[A-Za-z0-9](?:[A-Za-z0-9]|-(?=[A-Za-z0-9])){0,38}$";
+      "^[A-Za-z0-9](?:[A-Za-z0-9_]|-(?=[A-Za-z0-9])){0,38}$";
   public static final String VALID_GIT_SHA1 = "^[a-fA-F0-9]{40}$";
   public static final String GITHUB_URL = GitHubServerConfig.GITHUB_URL;
   public static final String GITHUB_COM = "github.com";
```
The Regex should be here.

because user-name_BLEH matches but in the current PR that does not match with Github EMU

2022-03-24 15:55 UTC, spstarr commented
Bug matching this issue is JENKINS-67946

2022-10-28 15:24 UTC, JeffCobble commented
Hi.  It looks like this PR has been open for a while but no movement on resolution?  My team is running into this issue and need this change merged for us to make use of forks to personal repos based on azure ad putting underscores in user names with EMU.

2022-10-28 22:28 UTC, rkivisto commented
I wrote a testcase for this over on https://github.com/jenkinsci/github-branch-source-plugin/pull/626

2022-11-03 14:14 UTC, rkivisto commented
#626 was merged and the fix for [JENKINS-67946](https://issues.jenkins.io/browse/JENKINS-67946) is now released in https://github.com/jenkinsci/github-branch-source-plugin/releases/tag/1696.v3a_7603564d04
This #421 PR can be closed, thanks everyone!

2022-11-03 17:05 UTC, closed without merging