Don't pull avatar if remote GitHub Enterprise uses private mode.
jenkinsci/github-branch-source-plugin pull request #532
Opened 2022-04-06 13:00 UTC by Vlatombe

# Description

When defining a GitHub organization pointing at a Github Enterprise instance running in private mode, the avatar URL can't be accessed directly. This is causing a broken icon to be displayed as well as layout problems in list view in recent Jenkins versions.

This patch detects if the remote instance is in private mode and fallbacks to the standard github icon in that case.
The organization folder needs to be saved after upgrading to apply the new logic.

Before
![Capture d’écran 2022-04-06 à 11 58 39](https://user-images.githubusercontent.com/171459/161979279-7ca22ddc-82b0-439c-a0d5-cb292830dc34.png)

After
![Capture d’écran 2022-04-06 à 14 59 49](https://user-images.githubusercontent.com/171459/161980234-a67c41d8-af18-4283-80e0-d9d3bf36008d.png)

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [ ] Automated tests have been added to exercise the changes
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verify that the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

# Documentation changes
- [ ] Link to jenkins.io PR, or an explanation for why no doc changes are needed

# Users/aliases to notify

2022-04-06 13:20 UTC, raul-arabaolaza approved these changes

2022-04-08 12:26 UTC, jtnord requested changes
I think this would be clearer if exceptions where not used to control the flow - especially for the majority use case.

2022-04-08 12:26 UTC, jtnord commented on src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigator.java
> +    String apiUri = getApiUri();
```suggestion
    String apiUri = Util.fixEmptyAndTrim(getApiUri());
```

2022-04-08 12:26 UTC, jtnord commented on src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigator.java
> +      // Ignored
```suggestion
      return true;  // URL is bogus so there is never going to be an avatar - or anything else come to think of it
```

2022-04-08 12:26 UTC, jtnord commented on src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigator.java
> +      if (e.getMessage().contains("private mode enabled")) {
https://github.com/hub4j/github-api/blob/a3a5a32e8d9447a46675d1439ba75e1e5a0ecf14/src/main/java/org/kohsuke/github/GitHubClient.java#L324-L327

2022-04-08 12:26 UTC, jtnord commented on src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigator.java
> +      GitHub.connectToEnterpriseAnonymously(new URL(apiUri).toString()).checkApiUrlValidity();
this look like an ugly and non intuitive way of saying - do not do a check if the URL is `null` however it also performs the check on github.com which would seem to be incorrect as this is only available in GHE?

```suggestion
    if (apiURL == null || apiURL.equals(GitHubServerConfig.GITHUB_URL)) {
      return false;
    }
    try {
      GitHub.connectToEnterpriseAnonymously(apiUri).checkApiUrlValidity();
```

2022-04-08 12:37 UTC, jtnord commented
Looking at this again - I do not think this is even the correct fix and only fixes half the issue (if the other half is fixed then this is not needed at all).

Basically the image is not loaded so the browser is falling back to what it should do - the "alt text"  (which is "GitHub Organisation")

if image loading is disabled you will see exactly the same issue against the public github.com (shown here for ci.jenkins.io)

<img width="409" alt="image" src="https://user-images.githubusercontent.com/494726/162436797-39a6a0b8-5a37-48dd-99c1-8f6dbe5e5dd2.png">

The issue would seem to be that the alt text is too wide for the column (and the column is not resizing) to accommodate it.

2022-04-08 15:10 UTC, jtnord commented on src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigator.java
> +    boolean privateMode = apiUri == null ? false : determinePrivateMode(apiUri);
@Vlatombe I missed one, sorry
```suggestion
    boolean privateMode = determinePrivateMode(apiUri);
```

2022-04-08 15:12 UTC, jtnord approved these changes

2022-04-11 13:49 UTC, jtnord commented on src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigator.java
> +    if (apiURL == null || apiURL.equals(GitHubServerConfig.GITHUB_URL)) {
```suggestion
    if (apiUri== null || apiUri.equals(GitHubServerConfig.GITHUB_URL)) {
```

2022-04-14 03:24 UTC, car-roll commented
Looks like there hasn't been an incremental generated since the first commit. Apparently they are just `spotless` errors 😞

2022-04-14 03:28 UTC, car-roll approved these changes

2022-05-03 16:57 UTC, merged